<div id="cam1267" class="cameraIcon" style="top:276px; left:102px;"><a href="default.aspx?cam=1267"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-5: SR-14" title="I-5: SR-14"/></a></div>
<div id="cam9289" class="cameraIcon" style="top:266px; left:103px;"><a href="default.aspx?cam=9289"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-5: S of 179th" title="I-5: S of 179th"/></a></div>
<div id="cam1543" class="cameraIcon" style="top:199px; left:92px;"><a href="default.aspx?cam=1543"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-5: Rush Rd" title="I-5: Rush Rd"/></a></div>
<div id="cam9339" class="cameraIcon" style="top:184px; left:87px;"><a href="default.aspx?cam=9339"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-5: US 12 Grand Mound" title="I-5: US 12 Grand Mound"/></a></div>
<div id="cam1287" class="cameraIcon" style="top:167px; left:93px;"><a href="default.aspx?cam=1287"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-5: Capitol Blvd" title="I-5: Capitol Blvd"/></a></div>
<div id="cam9054" class="cameraIcon" style="top:134px; left:127px;"><a href="default.aspx?cam=9054"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Southcenter" title="Southcenter"/></a></div>
<div id="cam1030" class="cameraIcon" style="top:121px; left:124px;"><a href="default.aspx?cam=1030"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Mercer St" title="Mercer St"/></a></div>
<div id="cam1036" class="cameraIcon" style="top:112px; left:124px;"><a href="default.aspx?cam=1036"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="NE 145th St" title="NE 145th St"/></a></div>
<div id="cam1042" class="cameraIcon" style="top:104px; left:127px;"><a href="default.aspx?cam=1042"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-5/I-405 Interchange (Alderwood)" title="I-5/I-405 Interchange (Alderwood)"/></a></div>
<div id="cam1316" class="cameraIcon" style="top:58px; left:124px;"><a href="default.aspx?cam=1316"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-5: College Way" title="I-5: College Way"/></a></div>
<div id="cam1054" class="cameraIcon" style="top:37px; left:121px;"><a href="default.aspx?cam=1054"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Lake Samish Park and Ride" title="Lake Samish Park and Ride"/></a></div>
<div id="cam1055" class="cameraIcon" style="top:18px; left:108px;"><a href="default.aspx?cam=1055"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Loomis Trail Rd" title="Loomis Trail Rd"/></a></div>
<div id="cam1057" class="cameraIcon" style="top:13px; left:103px;"><a href="default.aspx?cam=1057"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-5 @ Peace Arch" title="I-5 @ Peace Arch"/></a></div>
<div id="cam1100" class="cameraIcon" style="top:137px; left:173px;"><a href="default.aspx?cam=1100"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Snoqualmie Summit on I-90 @ MP52" title="Snoqualmie Summit on I-90 @ MP52"/></a></div>
<div id="cam9019" class="cameraIcon" style="top:149px; left:178px;"><a href="default.aspx?cam=9019"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Easton Hill on I-90 @ MP67.4" title="Easton Hill on I-90 @ MP67.4"/></a></div>
<div id="cam8094" class="cameraIcon" style="top:156px; left:193px;"><a href="default.aspx?cam=8094"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Bullfrog-facing east on I-90 @ MP 79.54" title="Bullfrog-facing east on I-90 @ MP 79.54"/></a></div>
<div id="cam1104" class="cameraIcon" style="top:158px; left:205px;"><a href="default.aspx?cam=1104"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Elk Heights on I-90 @ MP 92" title="Elk Heights on I-90 @ MP 92"/></a></div>
<div id="cam1107" class="cameraIcon" style="top:174px; left:249px;"><a href="default.aspx?cam=1107"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-90 MP 138 Vantage Br. (View West)" title="I-90 MP 138 Vantage Br. (View West)"/></a></div>
<div id="cam8076" class="cameraIcon" style="top:161px; left:272px;"><a href="default.aspx?cam=8076"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-90 MP 164.5 (View East)" title="I-90 MP 164.5 (View East)"/></a></div>
<div id="cam1110" class="cameraIcon" style="top:164px; left:298px;"><a href="default.aspx?cam=1110"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-90 MP 189 Warden Exit" title="I-90 MP 189 Warden Exit"/></a></div>
<div id="cam8313" class="cameraIcon" style="top:159px; left:331px;"><a href="default.aspx?cam=8313"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-90/US 395 Interchange @ Ritzville (4)" title="I-90/US 395 Interchange @ Ritzville (4)"/></a></div>
<div id="cam4015" class="cameraIcon" style="top:120px; left:375px;"><a href="default.aspx?cam=4015"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-90/SR-902" title="I-90/SR-902"/></a></div>
<div id="cam1127" class="cameraIcon" style="top:175px; left:220px;"><a href="default.aspx?cam=1127"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Manastash Ridge Summit on I-82 @ MP 7" title="Manastash Ridge Summit on I-82 @ MP 7"/></a></div>
<div id="cam4022" class="cameraIcon" style="top:192px; left:225px;"><a href="default.aspx?cam=4022"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Selah Creek Rest Area on I-82 @ MP22.4" title="Selah Creek Rest Area on I-82 @ MP22.4"/></a></div>
<div id="cam8061" class="cameraIcon" style="top:207px; left:222px;"><a href="default.aspx?cam=8061"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Union Gap on I-82" title="Union Gap on I-82"/></a></div>
<div id="cam4027" class="cameraIcon" style="top:220px; left:237px;"><a href="default.aspx?cam=4027"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Outlook on I-82 @ MP 58" title="Outlook on I-82 @ MP 58"/></a></div>
<div id="cam4028" class="cameraIcon" style="top:230px; left:261px;"><a href="default.aspx?cam=4028"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Prosser on I-82 @ MP 82" title="Prosser on I-82 @ MP 82"/></a></div>
<div id="cam9751" class="cameraIcon" style="top:227px; left:275px;"><a href="default.aspx?cam=9751"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Benton City on I-82 @ MP 96" title="Benton City on I-82 @ MP 96"/></a></div>
<div id="cam8096" class="cameraIcon" style="top:227px; left:281px;"><a href="default.aspx?cam=8096"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="I-82 @ I-182" title="I-82 @ I-182"/></a></div>
<div id="cam8084" class="cameraIcon" style="top:243px; left:289px;"><a href="default.aspx?cam=8084"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Horse Heaven Looking South on I-82 @ MP 121.2" title="Horse Heaven Looking South on I-82 @ MP 121.2"/></a></div>
<div id="cam4031" class="cameraIcon" style="top:251px; left:283px;"><a href="default.aspx?cam=4031"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Plymouth Port of Entry on I-82 @ MP131.5" title="Plymouth Port of Entry on I-82 @ MP131.5"/></a></div>
<div id="cam1525" class="cameraIcon" style="top:94px; left:133px;"><a href="default.aspx?cam=1525"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 2: Homeacres Rd" title="US 2: Homeacres Rd"/></a></div>
<div id="cam5000" class="cameraIcon" style="top:103px; left:142px;"><a href="default.aspx?cam=5000"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 2/SR 522" title="US 2/SR 522"/></a></div>
<div id="cam8062" class="cameraIcon" style="top:112px; left:188px;"><a href="default.aspx?cam=8062"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 2 MP 64.8 East Stevens Pass Summit" title="US 2 MP 64.8 East Stevens Pass Summit"/></a></div>
<div id="cam8083" class="cameraIcon" style="top:112px; left:207px;"><a href="default.aspx?cam=8083"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 2 MP 87 Winton" title="US 2 MP 87 Winton"/></a></div>
<div id="cam1343" class="cameraIcon" style="top:133px; left:228px;"><a href="default.aspx?cam=1343"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 2/97 MP 119 (View South)" title="US 2/97 MP 119 (View South)"/></a></div>
<div id="cam9250" class="cameraIcon" style="top:120px; left:243px;"><a href="default.aspx?cam=9250"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 2 MP 149 (View S.W.)" title="US 2 MP 149 (View S.W.)"/></a></div>
<div id="cam9285" class="cameraIcon" style="top:119px; left:285px;"><a href="default.aspx?cam=9285"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 2 MP 193.4 Coulee City" title="US 2 MP 193.4 Coulee City"/></a></div>
<div id="cam9464" class="cameraIcon" style="top:198px; left:173px;"><a href="default.aspx?cam=9464"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="White Pass Summit on US12 @ MP 150.9 - East" title="White Pass Summit on US12 @ MP 150.9 - East"/></a></div>
<div id="cam8078" class="cameraIcon" style="top:206px; left:356px;"><a href="default.aspx?cam=8078"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Delaney on US 12 @ MP 381.3" title="Delaney on US 12 @ MP 381.3"/></a></div>
<div id="cam1135" class="cameraIcon" style="top:206px; left:385px;"><a href="default.aspx?cam=1135"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Alpowa Summit on US-12 @ MP 413" title="Alpowa Summit on US-12 @ MP 413"/></a></div>
<div id="cam1136" class="cameraIcon" style="top:267px; left:203px;"><a href="default.aspx?cam=1136"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Maryhill" title="Maryhill"/></a></div>
<div id="cam1137" class="cameraIcon" style="top:249px; left:212px;"><a href="default.aspx?cam=1137"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Satus Pass on US 97 @ MP 27" title="Satus Pass on US 97 @ MP 27"/></a></div>
<div id="cam1138" class="cameraIcon" style="top:144px; left:216px;"><a href="default.aspx?cam=1138"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 97 MP 164 Blewett Pass Summit" title="US 97 MP 164 Blewett Pass Summit"/></a></div>
<div id="cam8068" class="cameraIcon" style="top:126px; left:215px;"><a href="default.aspx?cam=8068"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 97 MP 185 Don Senn Memorial Interchange" title="US 97 MP 185 Don Senn Memorial Interchange"/></a></div>
<div id="cam8091" class="cameraIcon" style="top:102px; left:250px;"><a href="default.aspx?cam=8091"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 97 MP 240 N. Chelan Falls" title="US 97 MP 240 N. Chelan Falls"/></a></div>
<div id="cam1139" class="cameraIcon" style="top:53px; left:271px;"><a href="default.aspx?cam=1139"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 97 MP 299 Riverside" title="US 97 MP 299 Riverside"/></a></div>
<div id="cam9022" class="cameraIcon" style="top:14px; left:272px;"><a href="default.aspx?cam=9022"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 97 MP 336.4 (View North)" title="US 97 MP 336.4 (View North)"/></a></div>
<div id="cam1140" class="cameraIcon" style="top:110px; left:236px;"><a href="default.aspx?cam=1140"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 97A MP 226 (View North)" title="US 97A MP 226 (View North)"/></a></div>
<div id="cam8069" class="cameraIcon" style="top:227px; left:39px;"><a href="default.aspx?cam=8069"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 101: Astoria-Megler Bridge" title="US 101: Astoria-Megler Bridge"/></a></div>
<div id="cam1141" class="cameraIcon" style="top:171px; left:49px;"><a href="default.aspx?cam=1141"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Cosmopolis Hill on US-101 @ MP 78" title="Cosmopolis Hill on US-101 @ MP 78"/></a></div>
<div id="cam1142" class="cameraIcon" style="top:156px; left:41px;"><a href="default.aspx?cam=1142"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="State Camp Hill on US-101 @ MP 100.5" title="State Camp Hill on US-101 @ MP 100.5"/></a></div>
<div id="cam8051" class="cameraIcon" style="top:125px; left:25px;"><a href="default.aspx?cam=8051"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Queets on  SR 101 @ MP 151.7" title="Queets on  SR 101 @ MP 151.7"/></a></div>
<div id="cam1143" class="cameraIcon" style="top:84px; left:35px;"><a href="default.aspx?cam=1143"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Heckelsville Shed on US 101 @ MP 214" title="Heckelsville Shed on US 101 @ MP 214"/></a></div>
<div id="cam8075" class="cameraIcon" style="top:85px; left:57px;"><a href="default.aspx?cam=8075"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Indian Valley on US 101 @ MP 237.2" title="Indian Valley on US 101 @ MP 237.2"/></a></div>
<div id="cam1144" class="cameraIcon" style="top:83px; left:75px;"><a href="default.aspx?cam=1144"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Siebert on US 101 @ MP 256" title="Siebert on US 101 @ MP 256"/></a></div>
<div id="cam1145" class="cameraIcon" style="top:87px; left:92px;"><a href="default.aspx?cam=1145"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Diamond Point on US 101 @ MP 275" title="Diamond Point on US 101 @ MP 275"/></a></div>
<div id="cam8050" class="cameraIcon" style="top:111px; left:95px;"><a href="default.aspx?cam=8050"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Mt Walker, SR-101@ 301.5" title="Mt Walker, SR-101@ 301.5"/></a></div>
<div id="cam8052" class="cameraIcon" style="top:162px; left:85px;"><a href="default.aspx?cam=8052"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Oyster Bay Rd. on SR 101 @ MP 359" title="Oyster Bay Rd. on SR 101 @ MP 359"/></a></div>
<div id="cam8032" class="cameraIcon" style="top:203px; left:405px;"><a href="default.aspx?cam=8032"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US-195 @ Uniontown" title="US-195 @ Uniontown"/></a></div>
<div id="cam4033" class="cameraIcon" style="top:173px; left:388px;"><a href="default.aspx?cam=4033"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 195 - Colfax" title="US 195 - Colfax"/></a></div>
<div id="cam8043" class="cameraIcon" style="top:133px; left:385px;"><a href="default.aspx?cam=8043"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US-195 @ Spangle 4" title="US-195 @ Spangle 4"/></a></div>
<div id="cam8031" class="cameraIcon" style="top:228px; left:293px;"><a href="default.aspx?cam=8031"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Blue Bridge on US 395 @ MP 19" title="Blue Bridge on US 395 @ MP 19"/></a></div>
<div id="cam9392" class="cameraIcon" style="top:187px; left:316px;"><a href="default.aspx?cam=9392"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US395 & SR26 / Hatton Coulee" title="US395 & SR26 / Hatton Coulee"/></a></div>
<div id="cam8240" class="cameraIcon" style="top:104px; left:382px;"><a href="default.aspx?cam=8240"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Little Spokane River on US 395 @ MP 168" title="Little Spokane River on US 395 @ MP 168"/></a></div>
<div id="cam8280" class="cameraIcon" style="top:91px; left:374px;"><a href="default.aspx?cam=8280"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Loon Lake Summit on US-395 @ MP 188 (1)" title="Loon Lake Summit on US-395 @ MP 188 (1)"/></a></div>
<div id="cam4035" class="cameraIcon" style="top:46px; left:349px;"><a href="default.aspx?cam=4035"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="US 395 - Colville - Canning" title="US 395 - Colville - Canning"/></a></div>
<div id="cam8234" class="cameraIcon" style="top:12px; left:336px;"><a href="default.aspx?cam=8234"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Laurier on US-395 @ MP 275 Position 5" title="Laurier on US-395 @ MP 275 Position 5"/></a></div>
<div id="cam1251" class="cameraIcon" style="top:221px; left:58px;"><a href="default.aspx?cam=1251"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="KM Mountain on SR 4 @ MP 22" title="KM Mountain on SR 4 @ MP 22"/></a></div>
<div id="cam9417" class="cameraIcon" style="top:188px; left:130px;"><a href="default.aspx?cam=9417"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 7: Elbe Bridge" title="SR 7: Elbe Bridge"/></a></div>
<div id="cam1151" class="cameraIcon" style="top:168px; left:82px;"><a href="default.aspx?cam=1151"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Rock Candy Mountain on SR-8 @ MP 16.1" title="Rock Candy Mountain on SR-8 @ MP 16.1"/></a></div>
<div id="cam4024" class="cameraIcon" style="top:109px; left:134px;"><a href="default.aspx?cam=4024"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 9: 228th St SE" title="SR 9: 228th St SE"/></a></div>
<div id="cam1154" class="cameraIcon" style="top:280px; left:127px;"><a href="default.aspx?cam=1154"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 14: CapeHorn" title="SR 14: CapeHorn"/></a></div>
<div id="cam9409" class="cameraIcon" style="top:275px; left:144px;"><a href="default.aspx?cam=9409"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 14: Bridge of the Gods" title="SR 14: Bridge of the Gods"/></a></div>
<div id="cam8070" class="cameraIcon" style="top:269px; left:167px;"><a href="default.aspx?cam=8070"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 14: Hood River Bridge" title="SR 14: Hood River Bridge"/></a></div>
<div id="cam9410" class="cameraIcon" style="top:274px; left:185px;"><a href="default.aspx?cam=9410"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 14: Dallesport" title="SR 14: Dallesport"/></a></div>
<div id="cam9302" class="cameraIcon" style="top:184px; left:295px;"><a href="default.aspx?cam=9302"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 17 MP 28.38 SR 26" title="SR 17 MP 28.38 SR 26"/></a></div>
<div id="cam1160" class="cameraIcon" style="top:106px; left:279px;"><a href="default.aspx?cam=1160"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 17 MP 112 E. Mansfield" title="SR 17 MP 112 E. Mansfield"/></a></div>
<div id="cam5010" class="cameraIcon" style="top:133px; left:146px;"><a href="default.aspx?cam=5010"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 18: Tiger Mountain" title="SR 18: Tiger Mountain"/></a></div>
<div id="cam4030" class="cameraIcon" style="top:61px; left:252px;"><a href="default.aspx?cam=4030"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 20 MP 214.5 (View East)" title="SR 20 MP 214.5 (View East)"/></a></div>
<div id="cam1161" class="cameraIcon" style="top:43px; left:325px;"><a href="default.aspx?cam=1161"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Sherman Pass on SR-20 @ MP 320" title="Sherman Pass on SR-20 @ MP 320"/></a></div>
<div id="cam8081" class="cameraIcon" style="top:206px; left:253px;"><a href="default.aspx?cam=8081"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 24 @ SR 241" title="SR 24 @ SR 241"/></a></div>
<div id="cam1295" class="cameraIcon" style="top:151px; left:249px;"><a href="default.aspx?cam=1295"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 28 MP 25 Quincy Rest Area" title="SR 28 MP 25 Quincy Rest Area"/></a></div>
<div id="cam9381" class="cameraIcon" style="top:145px; left:269px;"><a href="default.aspx?cam=9381"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 28 @ SR 282 (Ephrata)" title="SR 28 @ SR 282 (Ephrata)"/></a></div>
<div id="cam8098" class="cameraIcon" style="top:20px; left:381px;"><a href="default.aspx?cam=8098"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Metaline Falls on SR 31 @ MP 16.69" title="Metaline Falls on SR 31 @ MP 16.69"/></a></div>
<div id="cam9432" class="cameraIcon" style="top:103px; left:111px;"><a href="default.aspx?cam=9432"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Hood Canal Bridge Looking West" title="Hood Canal Bridge Looking West"/></a></div>
<div id="cam8053" class="cameraIcon" style="top:153px; left:27px;"><a href="default.aspx?cam=8053"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Pt. Grenville on SR 109 @ MP 36.5" title="Pt. Grenville on SR 109 @ MP 36.5"/></a></div>
<div id="cam9418" class="cameraIcon" style="top:75px; left:26px;"><a href="default.aspx?cam=9418"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 112 @ Burnt Mt" title="SR 112 @ Burnt Mt"/></a></div>
<div id="cam1176" class="cameraIcon" style="top:154px; left:127px;"><a href="default.aspx?cam=1176"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="SR 167/SR 410 Interchange" title="SR 167/SR 410 Interchange"/></a></div>
<div id="cam8099" class="cameraIcon" style="top:237px; left:269px;"><a href="default.aspx?cam=8099"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Sellards Road-SB facing on SR 221 @ MP13.5" title="Sellards Road-SB facing on SR 221 @ MP13.5"/></a></div>
<div id="cam9034" class="cameraIcon" style="top:208px; left:268px;"><a href="default.aspx?cam=9034"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Beloit Road on SR 240 @ MP8.2" title="Beloit Road on SR 240 @ MP8.2"/></a></div>
<div id="cam1252" class="cameraIcon" style="top:238px; left:89px;"><a href="default.aspx?cam=1252"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Lewis and Clark Bridge on SR-433" title="Lewis and Clark Bridge on SR-433"/></a></div>
<div id="cam9173" class="cameraIcon" style="top:94px; left:123px;"><a href="default.aspx?cam=9173"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="WSF Clinton Dock" title="WSF Clinton Dock"/></a></div>
<div id="cam1233" class="cameraIcon" style="top:49px; left:90px;"><a href="default.aspx?cam=1233"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="WSF Friday Harbor Ferry Holding" title="WSF Friday Harbor Ferry Holding"/></a></div>
<div id="cam1242" class="cameraIcon" style="top:224px; left:126px;"><a href="default.aspx?cam=1242"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Mount St. Helens" title="Mount St. Helens"/></a></div>
<div id="cam4038" class="cameraIcon" style="top:204px; left:125px;"><a href="default.aspx?cam=4038"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Morton" title="Morton"/></a></div>
<div id="cam1245" class="cameraIcon" style="top:186px; left:397px;"><a href="default.aspx?cam=1245"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Pullman" title="Pullman"/></a></div>
<div id="cam1350" class="cameraIcon" style="top:182px; left:157px;"><a href="default.aspx?cam=1350"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Mt. Rainier" title="Mt. Rainier"/></a></div>
<div id="cam1240" class="cameraIcon" style="top:96px; left:3px;"><a href="default.aspx?cam=1240"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="LaPush" title="LaPush"/></a></div>
<div id="cam1246" class="cameraIcon" style="top:55px; left:230px;"><a href="default.aspx?cam=1246"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Winthrop" title="Winthrop"/></a></div>
<div id="cam9350" class="cameraIcon" style="top:117px; left:342px;"><a href="default.aspx?cam=9350"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Davenport Airport - East" title="Davenport Airport - East"/></a></div>
<div id="cam8220" class="cameraIcon" style="top:116px; left:176px;"><a href="default.aspx?cam=8220"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Skykomish Airport East" title="Skykomish Airport East"/></a></div>
<div id="cam1340" class="cameraIcon" style="top:238px; left:339px;"><a href="default.aspx?cam=1340"><img src="//images.wsdot.wa.gov/traffic/camera.gif" class="cameraIcon" alt="Walla Walla Airport Southwest" title="Walla Walla Airport Southwest"/></a></div>